"""Aircraft maintenance reserve cash-flow engine."""

from .config import build_default_case
from .balances import (
    build_forecast_reserve_balances,
    build_full_reserve_balances,
    escalated_event_cost,
)
from .events import (
    build_forecast_maintenance_calendar,
    build_full_maintenance_calendar,
)
from .inflows import (
    build_forecast_reserve_inflows,
    build_full_reserve_inflows,
    escalated_reserve_rate,
)
from .models import (
    CaseInputs,
    ComponentConfig,
    EventDriver,
    ReserveBasis,
    UtilizationOverride,
)
from .lifecycle import (
    SCENARIO_SCHEMA_VERSION,
    AircraftAsset,
    AnalysisContext,
    ContractPeriod,
    CutoffPosition,
    KnownState,
    LeaseContract,
    ProrationConvention,
    RedeliveryConditionRule,
    ReserveAccountRule,
    ReserveCloseoutRule,
    Scenario,
    TerminalValue,
    TerminalValueBasis,
    TransitionPeriod,
    TransitionCost,
    UtilizationPattern,
    UtilizationRegime,
    build_contract_periods,
    lifecycle_segments,
    migrate_v1_case,
    scenario_to_v1_case,
)
from .utilization import build_forecast_utilization, build_full_utilization
from .lifecycle_utilization import (
    LIFECYCLE_UTILIZATION_COLUMNS,
    build_forecast_lifecycle_utilization,
    build_lifecycle_utilization,
)
from .contracts import (
    LEASE_CASHFLOW_COLUMNS,
    RESERVE_ACCOUNT_INFLOW_COLUMNS,
    ContractCashflowResult,
    build_contract_cashflows,
)
from .settlement import (
    COMPONENT_STATE_COLUMNS,
    LIFECYCLE_CASHFLOW_COLUMNS,
    MAINTENANCE_EVENT_COLUMNS,
    REDELIVERY_SETTLEMENT_COLUMNS,
    RESERVE_LEDGER_COLUMNS,
    SettlementResult,
    build_lifecycle_maintenance_events,
    build_lifecycle_settlement,
)
from .transitions import (
    ECONOMIC_CASHFLOW_COLUMNS,
    TRANSITION_CASHFLOW_COLUMNS,
    AlternativeSet,
    LifecycleEconomicsResult,
    ScenarioAlternative,
    build_lifecycle_economics,
    build_transition_cashflows,
)
from .valuation import (
    VALUATION_CASHFLOW_COLUMNS,
    VALUATION_SUMMARY_COLUMNS,
    ValuationResult,
    compare_alternatives,
)
from .v2_dashboard_service import build_v2_dashboard_payload
from .analysis import (
    AlternativeDiagnostic,
    DecisionAnalysis,
    build_decision_analysis,
    build_llm_explanation_payload,
)
from .sensitivity import (
    SensitivityResult,
    SensitivitySpec,
    SensitivityVariable,
    UNCERTAINTY_RANGE_COLUMNS,
    default_sensitivity_specs,
    run_sensitivity_analysis,
)

__all__ = [
    "CaseInputs",
    "ComponentConfig",
    "EventDriver",
    "ReserveBasis",
    "UtilizationOverride",
    "SCENARIO_SCHEMA_VERSION",
    "AircraftAsset",
    "AnalysisContext",
    "ContractPeriod",
    "CutoffPosition",
    "KnownState",
    "LeaseContract",
    "ProrationConvention",
    "RedeliveryConditionRule",
    "ReserveAccountRule",
    "ReserveCloseoutRule",
    "Scenario",
    "TerminalValue",
    "TerminalValueBasis",
    "TransitionPeriod",
    "TransitionCost",
    "UtilizationPattern",
    "UtilizationRegime",
    "build_contract_periods",
    "lifecycle_segments",
    "migrate_v1_case",
    "scenario_to_v1_case",
    "LIFECYCLE_UTILIZATION_COLUMNS",
    "build_forecast_lifecycle_utilization",
    "build_lifecycle_utilization",
    "LEASE_CASHFLOW_COLUMNS",
    "RESERVE_ACCOUNT_INFLOW_COLUMNS",
    "ContractCashflowResult",
    "build_contract_cashflows",
    "COMPONENT_STATE_COLUMNS",
    "LIFECYCLE_CASHFLOW_COLUMNS",
    "MAINTENANCE_EVENT_COLUMNS",
    "REDELIVERY_SETTLEMENT_COLUMNS",
    "RESERVE_LEDGER_COLUMNS",
    "SettlementResult",
    "build_lifecycle_maintenance_events",
    "build_lifecycle_settlement",
    "ECONOMIC_CASHFLOW_COLUMNS",
    "TRANSITION_CASHFLOW_COLUMNS",
    "AlternativeSet",
    "LifecycleEconomicsResult",
    "ScenarioAlternative",
    "build_lifecycle_economics",
    "build_transition_cashflows",
    "VALUATION_CASHFLOW_COLUMNS",
    "VALUATION_SUMMARY_COLUMNS",
    "ValuationResult",
    "compare_alternatives",
    "build_v2_dashboard_payload",
    "AlternativeDiagnostic",
    "DecisionAnalysis",
    "build_decision_analysis",
    "build_llm_explanation_payload",
    "SensitivityResult",
    "SensitivitySpec",
    "SensitivityVariable",
    "UNCERTAINTY_RANGE_COLUMNS",
    "default_sensitivity_specs",
    "run_sensitivity_analysis",
    "build_default_case",
    "build_forecast_reserve_balances",
    "build_forecast_maintenance_calendar",
    "build_forecast_reserve_inflows",
    "build_forecast_utilization",
    "build_full_maintenance_calendar",
    "build_full_reserve_balances",
    "build_full_reserve_inflows",
    "build_full_utilization",
    "escalated_reserve_rate",
    "escalated_event_cost",
]

__version__ = "2.0.0"
